version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
      - DATABASE_URL=file:./db/custom.db
    volumes:
      - ./db:/app/db
      - ./prisma/migrations:/app/prisma/migrations
    restart: unless-stopped
